steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - -c
      - |
        docker build -t europe-west9-docker.pkg.dev/microservices-shop-nestjs/image-registry/orders-ms -f dockerfile.prod --platform=linux/amd64 --build-arg ORDERS_DATABASE_URL=$$DATABASE_URL .
    secretEnv: ['DATABASE_URL']

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'europe-west9-docker.pkg.dev/microservices-shop-nestjs/image-registry/orders-ms',
      ]
options:
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
    - versionName: projects/74874566665/secrets/ORDERS_DATABASE_PROD_URL/versions/1
      env: 'DATABASE_URL'
